Fixes leak.
sbmlteam/libsbml pull request #168
Opened 2021-09-28 16:53 UTC by luciansmith

If a LineEnding has a child BoundingBox, the BoundingBox that was created at the beginning of the function is leaked in favor of the new one.  This fix doesn't create a blank bounding box unless one doesn't exist.

2021-09-28 20:31 UTC, luciansmith commented
Not sure how to test this in libsbml (do we do memory checks anywhere now?), but I can say that I've tested the fix in roadrunner and it worked there.

2021-10-01 19:22 UTC, luciansmith commented
I assume the failures are timeouts or the like, but I can't find where to tell it to re-run the failing tests.

2021-10-04 08:04 UTC, skeating requested changes
You'll need to merge the ubuntu fix that is now in development branch

2021-10-05 08:24 UTC, skeating approved these changes

2021-10-07 18:46 UTC, merged