Sk/small fixes
sbmlteam/libsbml pull request #392
Opened 2024-08-26 12:36 UTC by skeating

## Description
Fixes #367 

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Change in documentation

## Checklist:

- [ ] I have updated all documentation necessary.
- [ ] I have checked spelling in (new) comments.

## Testing
- [X] Testing is done automatically and codecov shows test coverage
- [ ] This cannot be tested automatically

2024-08-27 06:49 UTC, fbergmann requested changes
@skeating unfortunately, more files will need to be renamed. The following tests with packages fail: 

```
	 14 - test_extension_package_groups_run (Failed)
	 21 - test_multi_validator_run (Failed)
	 22 - test_extension_package_qual_run (Failed)
Errors while running CTest
```

2024-08-27 15:06 UTC, skeating commented
yes I know this extra fails that's why it's a draft pull request and I put an additional checkbox in that description 😸

2024-08-29 15:38 UTC, fbergmann requested changes
@skeating the multi test still seems to fail with: 


```
21: Testing General XML Consistency Constraints (20000 - 29999).
21: 
21: Error: 7020306-fail-01-01-10102.xml
21:   - Failures:  Expected: 2  Actual: 1
21: 
21: 
21: Error: 7020306-fail-01-01-10102.xml
21:   - Constraints:  Expected: 7020306  Actual: 
21: 7020306 
Error: e 9: (multi-20306 [Error]) There may be at most one ListOfCompartmentReferences container object within a Compartment object.
21: Reference: L3V1 Multi V1.1 Section 3.5.3
21:  Extended <compartment> may only have one <multi:listOfCompartmentReferences>
```

there is only one error reported, so it might need to be renamed as well?

2024-10-02 08:24 UTC, fbergmann approved these changes

2025-05-02 11:48 UTC, merged